#!/bin/sh

$LAMBDA_TASK_ROOT/jre11-slim/bin/java \
    --add-opens java.base/java.util=ALL-UNNAMED \
    -XX:+TieredCompilation \
    -XX:TieredStopAtLevel=1 \
    -XX:+UseSerialGC \
    -cp function.jar com.amazonaws.services.lambda.runtime.api.client.AWSLambda "$_HANDLER"
