AWSTemplateFormatVersion: "2010-09-09"
Description: flyway lambda with migration scripts in S3
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  S3Bucket:
    Type: String
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  DBSecretArn:
    Type: String
  DBSecretName:
    Type: String
  ConnectionString:
    Type: String
Resources:
  S3BucketMigrations:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3Bucket

  FlywayLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version : "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Join ['', ['arn:', !Ref 'AWS::Partition', ':iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole']]
      Policies:
        - PolicyName: "LambdaExecutionRolePolicy"
          PolicyDocument :
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:GetSecretValue"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                  - "s3:ListBucket"
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}"
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"

  FlywayLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Flyway lambda security group to access VPC
      VpcId: !Ref VPC

  DBFlywaySgRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt FlywayLambdaSecurityGroup.GroupId
      GroupId: !Ref RDSSecurityGroup

  FlywayLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: FlywayLambdaS3
      Code: flyway-all.jar
      Description: Flyway lambda
      Environment:
        Variables:
          DB_SECRET: !Ref DBSecretName
          DB_CONNECTION_STRING: !Ref ConnectionString
          S3_BUCKET: !Ref S3Bucket
      Handler: com.geekoosh.flyway.FlywayHandler::handleRequest
      MemorySize: 512
      Role: !GetAtt FlywayLambdaExecutionRole.Arn
      Runtime: java8
      Timeout: 120
      VpcConfig:
        SecurityGroupIds:
          - !Ref FlywayLambdaSecurityGroup
        SubnetIds: !Ref Subnets
