/*
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package com.ilmlf.customresource.utils;

import com.amazonaws.services.lambda.runtime.events.CloudFormationCustomResourceEvent;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

import java.util.Map;

@Data
/**
 * Properties that we include in the JSON response we send back to
 * CloudFormation. CloudFormation expects this response to be sent to a
 * presigned URL included in the request -- it doesn't look at the Lambda
 * response.
 *
 * @see <a href="https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html">Custom resource response objects</a>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CloudFormationCustomResourceOnEventResponse {
    /**
     * Must be either "SUCCESS" or "FAILED".
     */
    private String status;

    /**
     * The reason for a "FAILED" response.
     */
    private String reason = "";

    /**
     * An ID that CloudFormation will store and send along with any requests
     * related to the resource. Must be unique within this custom resource.
     *
     * In this Lambda, we use the numerical IDs that Datanet gives us.
     */
    private String physicalResourceId;

    /**
     * If true, CloudFormation will mask the output of the custom resource
     * when retrieving it with Fn::GetAtt.
     *
     * This is meant for sensitive data so we can probably leave it false.
     */
    private boolean noEcho;

    /**
     * Name-value pairs that consumers can retrieve with Fn::GetAtt.
     */
    private Map<String, Object> data;

    /* Properties that must be copied verbatim from the request. */

    /** The ARN of the stack containing the custom resource. */
    private String stackId;
    /** A unique ID for the request, generated by CloudFormation. */
    private String requestId;
    /** The name the template developer gave to the custom resource. */
    private String logicalResourceId;

    public static CloudFormationCustomResourceOnEventResponse fromEvent(CloudFormationCustomResourceEvent evt) {
        CloudFormationCustomResourceOnEventResponse result = new CloudFormationCustomResourceOnEventResponse();
        result.setStackId(evt.getStackId());
        result.setRequestId(evt.getRequestId());
        result.setLogicalResourceId(evt.getLogicalResourceId());

        result.setPhysicalResourceId(evt.getPhysicalResourceId());

        return result;
    }
}