language: java
jdk: openjdk8

services:
  - docker

before_deploy:
  - ./gradlew shadowJar

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/libs/*.jar
  file_glob: true
  skip_cleanup: true
  on:
    tags: true